using github actions

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,42 +10,63 @@ on:
     - main
 
 jobs:
-  ci:
+  mambaci:
     runs-on: ${{ matrix.os }}
     strategy:
       fail-fast: false
       matrix:
-        os: [ubuntu-latest]
+        os: [ubuntu-latest, macos-latest]
+
     steps:
       - uses: actions/checkout@v2
-      - name: install micromamba
+
+      - name: install mamba
+        uses: mamba-org/provision-with-micromamba@main
+        with:
+          environment-file: .ci/microenv.yaml
+          environment-name: microenv
         run: |
-          if [ "$RUNNER_OS" == "Linux" ]; then
-            wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba --strip-components=1
-          else
-            wget -qO- https://micromamba.snakepit.net/api/micromamba/osx-64/latest | tar -xvj bin/micromamba
-            mv bin/micromamba ./micromamba
-          fi
-          ./micromamba shell init -s bash -p ~/micromamba
-          mkdir -p ~/micromamba/pkgs/
-      - name: run tests
-        shell: bash -l {0}
-        run: |
-          export MAMBA_ROOT_PREFIX=~/micromamba
-          export MAMBA_EXE=$(pwd)/micromamba
-          . $MAMBA_ROOT_PREFIX/etc/profile.d/mamba.sh
           chmod +x .ci/test_project.sh || exit 1
           ./.ci/test_project.sh || exit 1
 
 
-      - name: Push
-        uses: s0/git-publish-subdir-action@develop
-        env:
-          REPO: self
-          BRANCH: rendered # The branch name where you want to push the assets
-          FOLDER: xeus-mylang # The directory where your assets are generated
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
-          MESSAGE: "added rendered: ({sha}) {msg}" # The commit message
+
+#  ci:
+#    runs-on: ${{ matrix.os }}
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        os: [ubuntu-latest]
+#    steps:
+#      - uses: actions/checkout@v2
+#      - name: install micromamba
+#        run: |
+#          if [ "$RUNNER_OS" == "Linux" ]; then
+#            wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba --strip-components=1
+#          else
+#            wget -qO- https://micromamba.snakepit.net/api/micromamba/osx-64/latest | tar -xvj bin/micromamba
+#            mv bin/micromamba ./micromamba
+#          fi
+#          ./micromamba shell init -s bash -p ~/micromamba
+#          mkdir -p ~/micromamba/pkgs/
+#      - name: run tests
+#        shell: bash -l {0}
+#        run: |
+#          export MAMBA_ROOT_PREFIX=~/micromamba
+#          export MAMBA_EXE=$(pwd)/micromamba
+#          . $MAMBA_ROOT_PREFIX/etc/profile.d/mamba.sh
+#          chmod +x .ci/test_project.sh || exit 1
+#          ./.ci/test_project.sh || exit 1
+#
+#
+#      - name: Push
+#        uses: s0/git-publish-subdir-action@develop
+#        env:
+#          REPO: self
+#          BRANCH: rendered # The branch name where you want to push the assets
+#          FOLDER: xeus-mylang # The directory where your assets are generated
+#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
+#          MESSAGE: "added rendered: ({sha}) {msg}" # The commit message
           
           
 #   test_win_shells:
